### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by joker2013** [NextronSystems/thor-lite#14]
OS 
docker hub ubuntu:latest

```
./thor/thor-lite-util 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8085c10]

runtime stack:
runtime.throw({0x8436a5d, 0x2a})
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/panic.go:1198 +0x6a
runtime.sigpanic()
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/signal_unix.go:719 +0x233
runtime.dropg(...)
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/proc.go:3419
runtime.goschedImpl(0x88001e0)
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/proc.go:3526 +0x70
runtime.gopreempt_m(0x88001e0)
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/proc.go:3559 +0x6f
runtime.newstack()
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/stack.go:1055 +0x3a0
runtime.morestack()
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/asm_386.s:455 +0x7c

goroutine 1 [runnable, locked to thread]:
runtime.init.6()
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/proc.go:293 +0x34
runtime.doInit(0x86bb980)
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/proc.go:6498 +0xf6
runtime.main()
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/proc.go:204 +0x14d
runtime.goexit()
        /home/tcagent/work/300e75c9bd0c6478-release-10.7.2/src/git.bsk/thorx/_3rdparty/tgt/golang-1.17.9/src/runtime/asm_386.s:1319 +0x1
```

**Comment by secDre4mer** [comment]
Hi,

Thanks for the report. Unfortunately, I can't reproduce the issue:

```
$ sudo docker run -v /tmp/ubuntu:/thorlite -it ubuntu:latest /thorlite/thor-lite-util
Jun  7 14:31:52 5fee3d50aac7 THOR_LITE_UTIL: Info: Read configuration from /thorlite/config/thor-util.yml
                                                                                 
    ________ ______  ___    __   ______________  __  ______________              
   /_  __/ // / __ \/ _ \  / /  /  _/_  __/ __/ / / / /_  __/  _/ /              
    / / / _  / /_/ / , _/ / /___/ /  / / / _/  / /_/ / / / _/ // /__             
   /_/ /_//_/\____/_/|_| /____/___/ /_/ /___/  \____/ /_/ /___/____/             
                                                                                 
   THOR Lite Update Utility                                                      
   Copyright by Nextron Systems GmbH, 2018                                       
   v1.10.6+thor10.7.2                                                            
                                                                                 
THOR 10 Update, Encryption & License Utility
...
```

Does this issue occur reproducibly on your machine? Based on the stack traces, the error is based in the Golang runtime and occurs before THOR Util execution starts.

**Comment by Neo23x0** [comment]
Could you run the "thor-util" on a different Linux system and tell us which version it is?

**Comment by secDre4mer** [comment]
Closed due to inactivity.
